/* ============================================================================
   ملف المحتوى | content.js
   ✏️  ده الملف الوحيد اللي تعدّل فيه عشان تغيّر أي نص في الموقع.
   - كل حقل ليه نسخة إنجليزي (en) وعربي (ar). غيّر اللي جوه " " وبس.
   - اللوجوهات والصور في مجلد assets/ . الباث مكتوب جنب كل عنصر.
   ============================================================================ */
window.CONTENT = {

  /* ===== 1) معلومات وروابط ===== */
  meta: {
    name:"Abdullah Basyoni", name_ar:"عبدالله بسيوني",
    role_en:"Digital Marketing Specialist", role_ar:"Digital Marketing Specialist",
    email:"abdullah.mohamed.basyouni@gmail.com",
    phone_label:"+20 109 589 5224", whatsapp:"201095895224",
    linkedin:"https://www.linkedin.com/in/abdullahbasyoni/", linkedin_label:"/abdullahbasyoni",
    location_en:"Alexandria, Egypt", location_ar:"الإسكندرية، مصر",
    socials:[
      {name:"LinkedIn",  key:"linkedin", url:"https://www.linkedin.com/in/abdullahbasyoni/"},
      {name:"Instagram", key:"instagram",url:"https://www.instagram.com/abdullah.basyoni/"},
      {name:"Facebook",  key:"facebook", url:"https://www.facebook.com/AbdullahBasyoni/?locale=ar_AR"},
      {name:"TikTok",    key:"tiktok",   url:"https://www.tiktok.com/@abdullah.basyoni"},
    ],
  },

  /* ===== 2) التنقل (صفحات) ===== */
  nav: [
    ["Home","الرئيسية","index.html"],
    ["About","عني","about.html"],
    ["Work","الشغل","work.html"],
    ["Services","الخدمات","services.html"],
    ["Contact","تواصل","contact.html"],
  ],
  nav_cta_en:"Let's talk", nav_cta_ar:"خلّينا نتكلم",

  /* ===== 3) الهيرو (الرئيسية) ===== */
  hero: {
    eyebrow_en:"Digital Marketing Specialist", eyebrow_ar:"Digital Marketing Specialist",
    title_en:["From chaos","to {clarity}."], title_ar:["من {التشتت}","إلى {الوضوح}."],
    sub_en:"I help brands move from chaos to clarity — in who they are, what they say, and where they stand in the market.",
    sub_ar:"بساعدك تنتقل من التشتت للوضوح — في نفسك، ورسالتك، ومكانك في السوق.",
    cta1_en:"Let's talk", cta1_ar:"يلا نتكلم",
    cta2_en:"See the work", cta2_ar:"شوف الشغل",
    slogan_en:"Try one more time", slogan_ar:"حاول كمان مرة",
    scroll_en:"Scroll", scroll_ar:"انزل",
  },

  /* ===== 4) الأرقام ===== */
  stats: [
    ["4","Years in marketing","سنين في التسويق"],
    ["36","Brands","براند"],
    ["100+","Campaigns","حملة"],
    ["5","MENA markets","أسواق"],
  ],

  /* ===== 5) كروت الرئيسية (مداخل للصفحات) ===== */
  homecards: [
    {t_en:"From reflections to strategy & marketing", t_ar:"من كتابة الخواطر للاستراتيجيات والتسويق",
     d_en:"How a writer became a marketer who builds clarity.", d_ar:"إزاي كاتب بقى ماركتير بيبني وضوح.",
     cta_en:"My story", cta_ar:"قصتي", link:"about.html"},
    {t_en:"12 featured cases · 36 brands", t_ar:"12 مشروع مميز · 36 براند",
     d_en:"Chaos turned into clarity, direction, and results across 5 markets.", d_ar:"فوضى اتحوّلت لوضوح واتجاه ونتائج في 5 أسواق.",
     cta_en:"The work", cta_ar:"الشغل", link:"work.html"},
    {t_en:"Strategy that moves business", t_ar:"استراتيجية بتحرّك البيزنس",
     d_en:"Content, campaigns, and systems — not just noise.", d_ar:"محتوى وحملات وأنظمة — مش مجرد دوشة.",
     cta_en:"What I do", cta_ar:"اللي بعمله", link:"services.html"},
  ],
  homecta_en:"Is your brand lost in the noise? Let's map its path through the market.",
  homecta_ar:"براندك تايه في الزحمة؟ خلّينا نرسملّه طريق في وسط السوق.",

  /* عنوان سيكشن الخدمات الماشي في الرئيسية */
  homeservices_eyebrow_en:"Services", homeservices_eyebrow_ar:"الخدمات",
  homeservices_title_en:"What I do", homeservices_title_ar:"اللي بعمله",

  /* وضع الـ 3D في الرئيسية: "words" كلمات | "icons" أيقونات */
  home3d_mode:"words",
  /* كلمات الـ 3D اللي بتتكوّن مع الاسكرول في الرئيسية (الجسيمات بتتجمّع عليها) */
  home3d_words_en:["GROWTH","STRATEGY","MARKETING","CLARITY","TRY AGAIN"],
  home3d_words_ar:["نمو","استراتيجية","تسويق","وضوح","حاول تاني"],

  /* نبذة تشويقية في الرئيسية (مع الصورة) */
  hometease: {
    eyebrow_en:"Who's behind this", eyebrow_ar:"مين ورا ده",
    body_en:"I'm Abdullah Basyoni — I help brands move from chaos to clarity: in who they are, their message, and their place in the market.",
    body_ar:"أنا عبدالله بسيوني، بدأت كاتب محتوى وكبرت لحد ما بقيت مسوّق متخصص في السوشيال ميديا والمحتوى. على مدى أكتر من 4 سنين اشتغلت مع براندات في مصر والسعودية والكويت ولبنان. شغلي ببساطة: أنقل البراند من إنه موجود وبس لإنه بيأثّر فعلًا — بمحتوى وكلام بيوصل للناس ويبني علاقة حقيقية. وبجمع بين الإبداع والتحليل، عشان القرارات تتبني على فهم مش على تخمين.
.",
    cta_en:"More about me", cta_ar:"اعرف عني أكتر",
    photo:"assets/photo.jpg",
  },

  /* ===== 6) القصة (About) ===== */
  story: {
    eyebrow_en:"The story", eyebrow_ar:"القصة",
    title_en:"How I got here", title_ar:"إزاي وصلت هنا",
    lead_en:"From a passion for writing to a coincidence that changed my path — all the way to today.",
    lead_ar:"من شغف في الكتابة، لصدفة غيّرت طريقي لحد النهاردة.",
    paras_en:[
      "I didn't come into marketing through textbooks or business school — I came in through writing. In 2019 I was writing stories, reflections, and emotional pieces, building a real connection with readers and the writing communities around me. One day, weighed down by sadness and a heavy sense of failure, I sat with a close friend — a digital marketer — and something struck me awake, like a pen that woke me up to this day. Over time that turned into a question I couldn't shake: why do some messages stay fixed in people's minds while others vanish completely? And how do I become a message that isn't forgotten?",
      "That question pulled me deeper into marketing. Between 2020 and 2022 I explored it from every angle — learning on YouTube, testing traditional tactics in different fields like outdoor, looking for where I truly belonged. I was as scattered as it gets back then — until I found my first company in 2022 and my first mentor. From there things took a new curve: one full of passion, love, and above all a hunger to learn this field. Since then I've worked across different markets — Egypt first, then Saudi Arabia, Kuwait, and Lebanon — and found the same problem repeating in every one:",
      "> Most brands weren't struggling because they lacked content — they were struggling from a lack of clarity, system, and direction, and worst of all, randomness in management and execution.",
      "That changed how I work. I stopped thinking like someone who just makes content and started thinking in strategy, campaigns, and operations — and how every piece ties to a real business outcome. I'm still learning: my goal right now is to grow into performance, and to develop SEO, automation, and scalable marketing systems. And no matter how hard or long the road gets, I remember my slogan: try one more time.",
    ],
    paras_ar:[
      "أنا مدخلتش الماركتنج من الكتب ولا من كليات إدارة الأعمال — أنا دخلته من الكتابة. سنة 2019 كنت بكتب قصص وخواطر ومحتوى بيلمس المشاعر، وبابني علاقة حقيقية مع القرّاء ومجتمعات الكتابة اللي حواليا. وفي يوم كان الحزن مسيطر عليا وإحساسي بالفشل محتوي عقلي، لحد ما قعدت مع صديقي اللي كان مسوّق إلكتروني، وضربني القلم اللي خلاني أفوق لحد النهاردة. والكلام ده مع الوقت اتحوّل لسؤال مكانش سايبني: ليه في رسايل بتفضل ثابتة في دماغ الناس، وفي رسايل تانية بتتنسي خالص؟ وإزاي أنا أكون رسالة ما تتنسيش؟",
      "السؤال ده هو اللي جرّني للماركتنج أكتر. وما بين 2020 و2022 جرّبته من كل ناحية — باتعلّم من يوتيوب، وبجرّب الطرق التقليدية في مجالات مختلفة زي الأوت دور، وبدوّر على المكان اللي أنا فعلاً بنتمي ليه. وكنت عشوائي لأبعد حد في الفترة دي، لحد ما لقيت أول شركة في 2022 وأول مينتور ليا، ومن هنا الموضوع بدأ ياخد منحنى تاني — منحنى مليان شغف وحب، والأهم جوع للتعلّم في المجال ده. ومن وقتها اشتغلت في أسواق مختلفة، بدأت مصر ثم السعودية والكويت ولبنان، ولقيت نفس المشكلة بتتكرر في كل سوق:",
      "> معظم البراندات مكانتش بتعاني من قلة المحتوى — كانت بتعاني من غياب الوضوح والنظام والاتجاه، والأسوأ العشوائية في الإدارة والتنفيذ.",
      "الكلام ده غيّر طريقة شغلي. بطّلت أفكّر كواحد بس بيعمل محتوى، وبدأت أفكّر باستراتيجية وحملات وأوبريشن، وإزاي كل حاجة بتتربط بنتيجة حقيقية للبيزنس. ولحد دلوقتي لسه بتعلّم — هدفي حاليًا أبقى performance وأطوّر الـ SEO والأتمتة وأنظمة التسويق اللي تقدر تكبر. ومهما الطريق كان صعب وطويل، هفتكر السلوجن بتاعي: حاول كمان مرة.",
    ],
  },

  /* ===== 7) الرؤية (About) ===== */
  approach: {
    eyebrow_en:"Approach", eyebrow_ar:"الرؤية",
    title_en:"How I See Marketing", title_ar:"إزاي بشوف التسويق",
    lead_en:"I don't believe marketing is a fixed formula. Every brand, market, and audience works differently — what wins for one can fail completely for another.",
    lead_ar:"أنا مش مؤمن إن التسويق معادلة ثابتة. كل براند وسوق وجمهور بيشتغل بشكل مختلف — اللي بينجح مع واحد ممكن يفشل تمامًا مع التاني.",
    chips_en:["understanding people","analyzing behavior","building direction","testing ideas","adapting continuously"],
    chips_ar:["فهم الناس","تحليل السلوك","بناء الاتجاه","اختبار الأفكار","التكيّف المستمر"],
    values_en:[["systems","over randomness"],["strategy","over imitation"],["learning","over pretending"],["results","that actually matter"]],
    values_ar:[["النظام","مش العشوائية"],["الاستراتيجية","مش التقليد"],["التعلّم","مش التظاهر"],["نتائج","ليها قيمة فعلًا"]],
    punch_en:"Marketing isn't only about being {seen}. It's about being {understood} — and making {sales}.",
    punch_ar:"التسويق مش بس إنك {تتشاف}. التسويق إنك {تتفهم وتحقق مبيعات}.",
  },

  /* ===== 8) الرحلة (About) ===== */
  journey: {
    eyebrow_en:"2019 → now", eyebrow_ar:"2019 ← الآن",
    title_en:"The Journey", title_ar:"الرحلة",
    items:[
      ["2019","Started with writing — stories, reflections, and emotional content that built early connections with online reading communities.","بدأت بالكتابة — قصص، خواطر، ومحتوى وجداني بنى أول علاقة مع مجتمعات القراءة أونلاين.",false],
      ["2020 — 2021","Discovered marketing and taught myself through online resources, experiments, and hands-on traditional marketing — including the cinema field.","اكتشفت التسويق واتعلّمت بنفسي من مصادر أونلاين وتجارب واحتكاك بالتسويق التقليدي في مجال السينمات.",false],
      ["2022","Stepped into digital marketing seriously through real projects — still searching for direction and clarity.","دخلت الديجيتال ماركتنج بجدية من خلال مشاريع حقيقية — ولسه بدوّر على الاتجاه الواضح ليا.",false],
      ["2023","Entered the industry professionally in my first digital marketing role — building a foundation in content, communication, and client work.","دخلت المجال احترافيًا في أول دور تسويقي — وبنيت أساس في المحتوى والتواصل وشغل العملاء.",false],
      ["2024","Expanded into Saudi Arabia and the wider MENA region — going deeper into strategy, campaign planning, operations, and solving marketing chaos inside teams.","اتوسّعت في السعودية ومنطقة الـ MENA — وغُصت أعمق في الاستراتيجية وتخطيط الحملات والأوبريشن وحل فوضى التسويق جوه التيمات.",false],
      ["2025 — Present","Focusing on SEO, paid media, automation, performance marketing, and SaaS environments — building a more structured, business-focused craft.","بركّز على الـ SEO والإعلانات المدفوعة والأتمتة وتسويق الأداء وبيئات الـ SaaS — وببني أساس منظم ومرتبط أكتر بالبيزنس.",true],
    ],
  },

  /* ===== 9) الشغل (Work) ===== */
  work: {
    eyebrow_en:"Case studies", eyebrow_ar:"دراسات حالة",
    title_en:"Work I'm proud of", title_ar:"شغل فخور بيه",
    lead_en:"36 brands across five markets. Here are the ones that best show the same idea at work: turning marketing chaos into clarity, direction, and results.",
    lead_ar:"36 براند عبر خمس أسواق. دي أكتر مشاريع بتوضّح نفس الفكرة شغّالة: تحويل فوضى التسويق لوضوح واتجاه ونتائج.",
    filters:[["all","All","الكل"],["strategy","Strategy","استراتيجية"],["social","Social Media","سوشيال ميديا"],["content","Content","محتوى"],["voice","Voice Over","Voice Over"]],
    cases:[
      {id:"mantorose",cat:"strategy",feat:true,brand:"Mantorose",logo:"assets/brands/mantorose.png",region_en:"KSA",region_ar:"السعودية",sector_en:"Drive-thru Coffee",sector_ar:"قهوة درايف-ثرو",role_en:"Marketing Strategist",role_ar:"استراتيجي تسويق",badge_en:"Turning point",badge_ar:"نقطة تحوّل",
       desc_en:"A full marketing strategy for an ~80-branch Saudi drive-thru coffee brand — research, positioning, audience, content, and an action plan to turn a scattered presence into a clear direction.",desc_ar:"استراتيجية تسويق متكاملة لبراند قهوة درايف-ثرو سعودي بـ~80 فرع — بحث وتموضع وجمهور ومحتوى وخطة عمل تحوّل الحضور المشتّت لاتجاه واضح.",
       challenge_en:"Despite ~80 branches, brand awareness lagged behind competitors and the visual identity was inconsistent — Mantorose needed sharper positioning and a stronger digital presence among Saudi youth.",challenge_ar:"رغم ~80 فرع، الوعي بالعلامة كان أقل من المنافسين والهوية البصرية مش متّسقة — مانتوروز محتاج تموضع أوضح وحضور رقمي أقوى وسط الشباب السعودي.",
       solution_en:"Built a full marketing strategy: brand foundation (mission, values, vision), situation and current-state analysis, a visual-identity audit, market and audience research, competitor analysis, a SWOT, a customer persona, a content plan, and an action plan.",solution_ar:"بنيت استراتيجية تسويق متكاملة: أساس البراند (الرسالة والقيم والرؤية)، تحليل الحالة والوضع الحالي، تدقيق الهوية البصرية، بحث السوق والجمهور، تحليل المنافسين، SWOT، شخصية العميل، خطة محتوى، وخطة عمل.",
       metric_en:"Full marketing strategy",metric_ar:"استراتيجية تسويق متكاملة",
       about_en:"Mantorose is a Saudi drive-thru coffee brand with around 80 branches, serving hot and cold beverages built on speed, quality, and cleanliness — a quick, reliable coffee stop.",
       about_ar:"Mantorose براند قهوة درايف-ثرو سعودي بحوالي 80 فرع، بيقدّم مشروبات ساخنة وباردة قايمة على السرعة والجودة والنظافة — محطة قهوة سريعة وموثوقة.",
       services_en:["Marketing strategy","Market & audience research","Competitor analysis","SWOT analysis","Brand positioning","Customer persona","Content plan","Visual identity audit","Action plan"],
       services_ar:["استراتيجية تسويق","بحث سوق وجمهور","تحليل المنافسين","تحليل SWOT","تموضع العلامة","شخصية العميل","خطة محتوى","تدقيق الهوية البصرية","خطة عمل"],
       results_en:["A complete, presentation-ready strategy — from brand foundation to action plan","Clear positioning and a customer persona for Saudi youth (~90% of the audience)","Content plan and action roadmap to lift awareness, digital presence, and revenue"],
       results_ar:["استراتيجية متكاملة جاهزة للعرض — من أساس البراند لخطة العمل","تموضع واضح وشخصية عميل للشباب السعودي (~90% من الجمهور)","خطة محتوى وخطة عمل لرفع الوعي والحضور الرقمي والإيرادات"],
       pdfs:[{file:"assets/work/mantorose/mantorose-marketing-strategy.pdf",label_en:"Marketing strategy (full deck)",label_ar:"استراتيجية التسويق (العرض الكامل)"}]},
      {id:"aone",cat:"content",feat:true,brand:"A_ONE",logo:"assets/brands/aone.png",region_en:"Egypt",region_ar:"مصر",sector_en:"Security & Networks",sector_ar:"أنظمة أمن وشبكات",role_en:"Content Supervisor & Content Writer",role_ar:"مشرف ومحرّر محتوى",badge_en:"Best numbers",badge_ar:"أقوى أرقام",
       desc_en:"Rebuilt content direction around a structured monthly plan and a shift to video-first content — turning a quiet account into measurable reach.",desc_ar:"أعدت بناء اتجاه المحتوى بخطة شهرية منظّمة وتحويل لمحتوى video-first — وحوّلت أكاونت هادي لـ reach يتقاس.",
       challenge_en:"Grow reach and engagement from a low base, with weak video performance.",challenge_ar:"زيادة الوصول والتفاعل من قاعدة منخفضة، مع أداء فيديو ضعيف.",
       solution_en:"Structured monthly content plan with clear goals, a shift to video-first content, and simplified messaging for technical products.",solution_ar:"خطة محتوى شهرية بأهداف واضحة، تحويل لمحتوى video-first، وتبسيط رسالة المنتجات التقنية.",
       metric_en:"+632% impressions · +740% 3-sec video views (90 days)",metric_ar:"+632% impressions · +740% مشاهدات فيديو (90 يوم)",
       /* ↓↓↓ حقول صفحة العميل المستقلة (كلها اختيارية — امسح اللي مش محتاجه) ↓↓↓ */
       about_en:"A_ONE is an Egyptian company specialized in security and networking systems — surveillance cameras, access control, and IT infrastructure for businesses and institutions.",
       about_ar:"A_ONE شركة مصرية متخصصة في أنظمة الأمن والشبكات — كاميرات مراقبة، أنظمة دخول، وبنية تقنية للشركات والمؤسسات.",
       duration_en:"90 days", duration_ar:"90 يوم",
       services_en:["Content strategy","Monthly content plan","Video-first content","Technical copywriting","Performance analysis"],
       services_ar:["استراتيجية محتوى","خطة محتوى شهرية","محتوى Video-first","كتابة تقنية مبسّطة","تحليل أداء"],
       results_en:["+632% impressions in 90 days","+740% 3-second video views","A quiet account turned into measurable, repeatable reach"],
       results_ar:["+632% impressions خلال 90 يوم","+740% مشاهدات فيديو (3 ثواني)","أكاونت هادي اتحوّل لـ reach يتقاس ويتكرر"],
       gallery:[
         {src:"assets/work/aone/aone-performance.png", cap_en:"90-day performance — +632% impressions, +740% 3-sec video views", cap_ar:"أداء 90 يوم — +632% ظهور، +740% مشاهدات فيديو (3 ثواني)"},
         {src:"assets/work/aone/aone-reach.png", cap_en:"90-day reach — 18,927 impressions, 2,472 engagements, 378 net followers", cap_ar:"وصول 90 يوم — 18,927 ظهور، 2,472 تفاعل، 378 صافي متابعين"},
         {src:"assets/work/aone/aone-page.png", cap_en:"A_ONE page — 2,013 followers", cap_ar:"صفحة A_ONE — 2,013 متابع"},
       ],
       pdfs:[ {file:"assets/work/aone/aone-content-plan.pdf", label_en:"Monthly content plan (sample)", label_ar:"خطة المحتوى الشهرية (نموذج)"} ]},
      {id:"sitdown",cat:"content",feat:true,brand:"Sitdown",logo:"assets/brands/sitdown.png",region_en:"KSA",region_ar:"السعودية",sector_en:"English Learning App",sector_ar:"تطبيق تعلّم إنجليزي",role_en:"Content Writer",role_ar:"كاتب محتوى",badge_en:"Growth",badge_ar:"نمو",
       desc_en:"Content for a Saudi English-learning app — I wrote the hooks and a full creative brief for each post, turning 'fear of speaking' and 'English is expensive' into simple, scroll-stopping ideas.",desc_ar:"محتوى لتطبيق تعلّم إنجليزي سعودي — كتبت الهوكس وبريف إبداعي كامل لكل بوست، وحوّلت «الخوف من الكلام» و«الإنجليزي غالي» لأفكار بسيطة بتوقّف العين.",
       challenge_en:"Learning English felt intimidating and expensive, and speaking was the biggest fear — the app needed content that made it feel easy, affordable, and worth starting.",challenge_ar:"تعلّم الإنجليزي كان مخيف وغالي، والكلام أكبر حاجز — التطبيق محتاج محتوى يخليه سهل وفي المتناول ويستاهل تبدأ.",
       solution_en:"As content writer I wrote the campaign copy and a full creative brief for each post — the hook plus the exact visual direction — across themes: breaking the fear of speaking, learning for the price of a coffee, kids' learning, careers and CVs, summer, and making friends worldwide.",solution_ar:"ككاتب محتوى كتبت كوبي الحملة وبريف إبداعي كامل لكل بوست — الهوك + التوجيه البصري بالظبط — عبر ثيمات: كسر حاجز الكلام، التعلّم بثمن قهوة، تعليم الأطفال، الكاريير والـ CV، الصيف، وصداقات حول العالم.",
       metric_en:"867 followers in 3 months",metric_ar:"867 متابع في 3 شهور",
       about_en:"Sitdown is a Saudi app for learning English through real conversation with teachers — affordable, practical, and built to get people actually speaking.",
       about_ar:"Sitdown تطبيق سعودي لتعلّم الإنجليزي من خلال محادثة حقيقية مع مدرّسين — في المتناول وعملي ومصمّم إنه يخلّي الناس تتكلم فعلاً.",
       services_en:["Copywriting","Social content","Creative direction (briefs)","Campaign concepts","Content planning"],
       services_ar:["كتابة محتوى","محتوى سوشيال","توجيه إبداعي (بريفات)","كونسبتات حملات","تخطيط محتوى"],
       results_en:["A full social campaign: 20+ post concepts, each with a written hook and art direction","Turned abstract objections (fear, cost, time) into simple, relatable ideas","867 followers in the first 3 months"],
       results_ar:["حملة سوشيال كاملة: +20 كونسبت بوست، كل واحد بهوك مكتوب وتوجيه فني","حوّلت اعتراضات مجرّدة (الخوف، السعر، الوقت) لأفكار بسيطة وقريبة","867 متابع في أول 3 شهور"],
       links:[{url:"https://www.instagram.com/appsitdown/",label_en:"Instagram",label_ar:"إنستجرام"},{url:"https://docs.google.com/spreadsheets/d/1FerrBjUZE8ShuQRwkS5ZKppG_p-O2VPmoS1NK9llTCM/edit?usp=sharing",label_en:"Content & design brief (Google Sheet)",label_ar:"بريف المحتوى والتصميم (Google Sheet)"}]},
      {id:"karaminn",cat:"strategy",brand:"Karam Inn",logo:"assets/brands/karaminn.png",region_en:"KSA",region_ar:"السعودية",sector_en:"Luxury Serviced Apartments",sector_ar:"شقق فندقية فاخرة",role_en:"Content Strategy & Project Coordinator",role_ar:"استراتيجية محتوى وتنسيق مشروع",
       desc_en:"Full content strategy for a new luxury serviced-apartments brand in Riyadh — market and competitor analysis, five buyer personas, messaging, and a four-week content calendar — plus a rebuilt ClickUp workflow that turned team chaos into an on-schedule operation.",desc_ar:"استراتيجية محتوى كاملة لبراند شقق فندقية فاخرة جديد في الرياض — تحليل سوق ومنافسين، 5 شخصيات مشترِية، رسائل، وتقويم محتوى لأربع أسابيع — بالإضافة لإعادة بناء سير العمل على ClickUp حوّل فوضى الفريق لعملية منضبطة.",
       challenge_en:"A brand-new entrant with near-zero market share in Riyadh's crowded serviced-apartments space — and a team with no clear content direction or schedule.",challenge_ar:"براند جديد بحصة سوقية شبه منعدمة في سوق الشقق الفندقية المزدحم بالرياض — وفريق من غير اتجاه أو جدول محتوى واضح.",
       solution_en:"I built the full content strategy: a five-year market analysis, a SWOT-based breakdown of four competitors, five buyer personas, key messages and tone of voice, a channel plan, and a four-week content calendar (12 posts + 8 videos a month). Then I rebuilt the team's workflow on ClickUp so everything shipped on schedule.",solution_ar:"بنيت استراتيجية المحتوى كاملة: تحليل سوق لخمس سنوات، تحليل SWOT لأربعة منافسين، 5 شخصيات مشترِية، رسائل ونبرة صوت، خطة قنوات، وتقويم محتوى لأربع أسابيع (12 بوست + 8 فيديوهات شهريًا). وبعدين أعدت بناء سير عمل الفريق على ClickUp عشان كل حاجة تنزل في معادها.",
       metric_en:"Full content strategy · 5 personas · 4-week calendar",metric_ar:"استراتيجية محتوى كاملة · 5 شخصيات · تقويم 4 أسابيع",
       about_en:"Karam Inn is a luxury serviced-apartments brand in the heart of Riyadh, owned and managed by Meter Property — blending authentic Saudi hospitality with modern living, minutes from KAFD and aligned with Vision 2030.",
       about_ar:"Karam Inn براند شقق فندقية فاخرة في قلب الرياض، مملوك ومُدار من متر العقار — بيمزج الضيافة السعودية الأصيلة بالحياة العصرية، على بُعد دقائق من «كافد» ومتماشي مع رؤية 2030.",
       services_en:["Content strategy","Market & competitor analysis","Buyer personas","Messaging & tone of voice","Content calendar","Workflow setup (ClickUp)"],
       services_ar:["استراتيجية محتوى","تحليل سوق ومنافسين","شخصيات مشترِية","الرسائل ونبرة الصوت","تقويم محتوى","إعداد سير العمل (ClickUp)"],
       results_en:["A complete content strategy: 5-year market analysis + SWOT on 4 competitors","5 buyer personas mapped to channels and messaging","A 4-week content calendar — 12 posts and 8 videos a month","Workflow rebuilt on ClickUp; content shipped on schedule"],
       results_ar:["استراتيجية محتوى متكاملة: تحليل سوق 5 سنوات + SWOT لأربعة منافسين","5 شخصيات مشترِية مربوطة بالقنوات والرسائل","تقويم محتوى لأربع أسابيع — 12 بوست و8 فيديوهات شهريًا","إعادة بناء سير العمل على ClickUp؛ المحتوى بينزل في معاده"],
       gallery:[{src:"assets/work/karaminn/karaminn-instagram.jpg",cap_en:"Published Instagram grid — the content live",cap_ar:"جريد إنستجرام بعد النشر — المحتوى شغّال"},{src:"assets/work/karaminn/karaminn-competitor.jpg",cap_en:"Competitor analysis (SWOT)",cap_ar:"تحليل المنافسين (SWOT)"},{src:"assets/work/karaminn/karaminn-persona.jpg",cap_en:"Buyer persona",cap_ar:"شخصية مشترِية"},{src:"assets/work/karaminn/karaminn-calendar.jpg",cap_en:"Weekly content calendar",cap_ar:"تقويم المحتوى الأسبوعي"}],
       pdfs:[{file:"assets/work/karaminn/karaminn-content-strategy.pdf",label_en:"Content strategy deck",label_ar:"عرض استراتيجية المحتوى"},{file:"assets/work/karaminn/karaminn-profile-en.pdf",label_en:"Brand profile (EN)",label_ar:"بروفايل البراند (إنجليزي)"},{file:"assets/work/karaminn/karaminn-profile-ar.pdf",label_en:"Brand profile (AR)",label_ar:"بروفايل البراند (عربي)"}]},
      {id:"broasted",cat:"social",brand:"Broasted Karam",logo:"assets/brands/broasted.png",region_en:"KSA",region_ar:"السعودية",sector_en:"Fried Chicken Restaurant",sector_ar:"مطعم بروستد",role_en:"Social Media Specialist & Content Writer",role_ar:"أخصائي سوشيال وكاتب محتوى",
       desc_en:"Ramadan social campaign for a Saudi fried-chicken brand — I wrote the strategy, the captions, the master video script, and the interactive stories around one idea: crispy comfort after a long day of fasting and work.",desc_ar:"حملة سوشيال رمضانية لبراند بروستد سعودي — كتبت الاستراتيجية والكابشن وسيناريو الفيديو الأساسي والستوريز التفاعلية حوالين فكرة واحدة: قرمشة تريّح بعد يوم طويل من الصيام والشغل.",
       challenge_en:"A neglected, low-impact social presence — and a need to connect young residents (many living in KSA away from family) with the brand during Ramadan.",challenge_ar:"حضور سوشيال مهمَل وضعيف — ومحتاج يربط الشباب المقيمين (كتير منهم عايش في السعودية بعيد عن أهله) بالبراند في رمضان.",
       solution_en:"I built the full Ramadan campaign: objective, audience, key messages and a friendly, spontaneous tone — then 12 posts, 2 videos and 7 interactive stories, with the captions, hashtags, a master video script (the now-signature car scene) and the shooting brief.",solution_ar:"بنيت حملة رمضان كاملة: الهدف، الجمهور، الرسائل، ونبرة ودودة عفوية — وبعدها 12 بوست و2 فيديو و7 ستوريز تفاعلية، مع الكابشن والهاشتاجات وسيناريو الفيديو الأساسي (مشهد السيارة المميّز) وبريف التصوير.",
       metric_en:"Ramadan campaign · 12 posts · 2 videos · 7 stories",metric_ar:"حملة رمضان · 12 بوست · 2 فيديو · 7 ستوريز",
       about_en:"Broasted Karam is a Saudi fried-chicken brand (Dammam) known for crispy broasted chicken, tenders and signature sauces — with a young, social-first audience.",
       about_ar:"Broasted Karam براند بروستد سعودي (الدمام) معروف بالدجاج المقرمش والأصابع والصوصات المميزة — وجمهوره شبابي وسوشيال أول.",
       services_en:["Content strategy","Copywriting","Social campaign","Video scriptwriting","Stories & interactive","Hashtag strategy","Art direction (shoot brief)"],
       services_ar:["استراتيجية محتوى","كتابة محتوى","حملة سوشيال","كتابة سيناريو فيديو","ستوريز وتفاعل","استراتيجية هاشتاجات","توجيه فني (بريف تصوير)"],
       results_en:["A full Ramadan campaign: 12 posts, 2 videos and 7 interactive stories","Wrote every caption plus a master video script — the car-scene concept","One clear theme: crispy comfort after a long day, built around youth living away from family","Friendly, interactive tone with polls, quizzes and a giveaway"],
       results_ar:["حملة رمضان كاملة: 12 بوست و2 فيديو و7 ستوريز تفاعلية","كتبت كل كابشن + سيناريو الفيديو الأساسي — كونسبت مشهد السيارة","ثيم واحد واضح: قرمشة تريّح بعد يوم طويل، مبني على الشباب البعيد عن أهله","نبرة ودودة وتفاعلية فيها تصويتات وكويزات ومسابقة"],
       videos:[{src:"assets/work/broasted/broasted-master.mp4",poster:"assets/work/broasted/broasted-master-poster.jpg",cap_en:"Master campaign film — \"Karam for everyone\" (the car-scene concept I scripted)",cap_ar:"فيلم الحملة الأساسي — «كله كرم» (كونسبت مشهد السيارة اللي كتبته)"},{src:"assets/work/broasted/broasted-reel.mp4",poster:"assets/work/broasted/broasted-reel-poster.jpg",cap_en:"Reel — \"Who wants some?\"",cap_ar:"ريل — «الكرم معي مين يبي؟»"}],
       gallery:[{src:"assets/work/broasted/broasted-night.jpg",cap_en:"The night-drive concept from the campaign film",cap_ar:"كونسبت الجولة الليلية من فيلم الحملة"},{src:"assets/work/broasted/broasted-car-eating.jpg",cap_en:"Crispy comfort after a long day",cap_ar:"قرمشة تريّح بعد يوم طويل"},{src:"assets/work/broasted/broasted-share.jpg",cap_en:"The lunch table brings everyone together",cap_ar:"السفرة بتجمعنا"},{src:"assets/work/broasted/broasted-dip.jpg",cap_en:"The sauce that sets the taste",cap_ar:"الصوص اللي يظبط الطعم"},{src:"assets/work/broasted/broasted-tray-car.jpg",cap_en:"A drive-thru moment",cap_ar:"لحظة من السيارة"},{src:"assets/work/broasted/broasted-crunch.jpg",cap_en:"Crunch in close-up",cap_ar:"القرمشة من قريب"},{src:"assets/work/broasted/broasted-redcar.jpg",cap_en:"The taste you order every day",cap_ar:"الطعم اللي تطلبه كل يوم"},{src:"assets/work/broasted/broasted-reel-still.jpg",cap_en:"Reel still — first bite",cap_ar:"لقطة من الريل — أول قضمة"},{src:"assets/work/broasted/broasted-eid.jpg",cap_en:"Eid greeting post",cap_ar:"بوست تهنئة العيد"},{src:"assets/work/broasted/broasted-contest.jpg",cap_en:"Engagement post — win SAR 500",cap_ar:"بوست مسابقة — اربح ٥٠٠ ريال"}],
       links:[{url:"https://www.instagram.com/broasted_karam/?hl=ar",label_en:"View the page on Instagram",label_ar:"شوف الصفحة على إنستجرام"}],
       pdfs:[{file:"assets/work/broasted/broasted-campaign.pdf",label_en:"Ramadan campaign deck",label_ar:"عرض حملة رمضان"}]},
      {id:"kiin",cat:"social",brand:"KIIN",logo:"assets/brands/kiin.png",region_en:"KSA",region_ar:"السعودية",sector_en:"Gourmet Fried Chicken",sector_ar:"دجاج جورميه",role_en:"Social Media Specialist & Content Writer",role_ar:"أخصائي سوشيال وكاتب محتوى",
       desc_en:"Ramadan social campaign for a Saudi gourmet-chicken brand — I built the concept and slogan, a full 12-post content calendar, and two on-ground activation ideas, all around one line: Kiin is the new touch that makes Ramadan tastier.",desc_ar:"حملة سوشيال رمضانية لبراند دجاج جورميه سعودي — بنيت الكونسبت والشعار، وكاليندر محتوى كامل ١٢ بوست، وفكرتين تفعيل على الأرض، كلها حوالين سطر واحد: كيين هي اللمسة الجديدة اللي بتخلّي رمضان أطعم.",
       challenge_en:"A weak, unfocused social presence — in a crowded Ramadan where every food brand says the same thing.",challenge_ar:"حضور سوشيال ضعيف وغير مركّز — وفي زحمة رمضان اللي كل براند أكل بيقول فيها نفس الكلام.",
       solution_en:"I built the full campaign: the concept (\"Kiin is the missing touch in Ramadan\"), the slogan, the audience and the tone — then a 12-post calendar (static + video) with every caption, hashtag and designer/video brief, plus two on-ground activations (the Neighbor's Box and \"Mufattir Kiin\") and a UGC + influencer plan.",solution_ar:"بنيت الحملة كاملة: الكونسبت («كيين هي اللمسة الناقصة في رمضان»)، الشعار، الجمهور والنبرة — وبعدها كاليندر ١٢ بوست (ستاتيك + فيديو) بكل كابشن وهاشتاج وبريف ديزاينر/فيديو، زائد فكرتين تفعيل على الأرض (بوكس الجار و«مفطّر كيين») وخطة UGC وإنفلونسرز.",
       metric_en:"Ramadan campaign · 12-post calendar · 2 activations",metric_ar:"حملة رمضان · كاليندر ١٢ بوست · فكرتين تفعيل",
       about_en:"KIIN is a Saudi gourmet fried-food brand (Dammam) — Korean-style fried chicken, smashed burgers and signature sandwiches, with a young, social-first audience.",
       about_ar:"كيين براند أكل جورميه سعودي (الدمام) — دجاج كوري مقلي، برجر سماش وساندوتشات مميّزة، وجمهوره شبابي وسوشيال أول.",
       services_en:["Content strategy","Campaign concept","Copywriting","Social calendar","Video briefs","Activation ideas","Hashtag strategy","UGC & influencer plan"],
       services_ar:["استراتيجية محتوى","كونسبت حملة","كتابة محتوى","كاليندر سوشيال","بريفات فيديو","أفكار تفعيل","استراتيجية هاشتاجات","خطة UGC وإنفلونسرز"],
       results_en:["A full Ramadan content calendar — 12 posts (static + video) mapped across the month","Campaign concept and slogan: \"Ramadan Kiin — tastier flavor, epic vibe\"","Every caption, hashtag set and designer/video brief, written end to end","Two on-ground activations: the Neighbor's Box (#Kiin_for_the_seventh_neighbor) and \"Mufattir Kiin\" — a Ramadan twist on the suhoor drummer","A UGC + influencer plan: spicy challenge, build-your-own meal, and a blogger series"],
       results_ar:["كاليندر محتوى رمضاني كامل — ١٢ بوست (ستاتيك + فيديو) موزّعين على الشهر","كونسبت الحملة والشعار: «رمضان كيين، طعمه أحلى وجوّه خطير»","كل كابشن وهاشتاج وبريف ديزاينر/فيديو، مكتوبين من الألف للياء","فكرتين تفعيل على الأرض: بوكس الجار (#كيين_لسابع_جار) و«مفطّر كيين» — تويست رمضاني على المسحّراتي","خطة UGC وإنفلونسرز: تحدي الحار، صمّم وجبتك، وسلسلة بلوجرز"],
       gallery:[{src:"assets/work/kiin/g1.jpg",cap_en:"Campaign key visual — \"tastier flavor, epic vibe\"",cap_ar:"كي فيجوال الحملة — «طعمه أحلى وجوّه خطير»"},{src:"assets/work/kiin/g2.jpg",cap_en:"Campaign key visual",cap_ar:"كي فيجوال من الحملة"},{src:"assets/work/kiin/g3.jpg",cap_en:"The signature chicken sandwich",cap_ar:"ساندوتش الدجاج المميّز"},{src:"assets/work/kiin/g4.jpg",cap_en:"The Ramadan table, Kiin style",cap_ar:"سفرة رمضان على طريقة كيين"},{src:"assets/work/kiin/g5.jpg",cap_en:"Ramadan group offers",cap_ar:"عروض رمضان للصحبة"},{src:"assets/work/kiin/g6.jpg",cap_en:"The Korean iftar offer",cap_ar:"عرض الفطور الكوري"},{src:"assets/work/kiin/g7.jpg",cap_en:"Korean fried chicken",cap_ar:"دجاج كوري مقلي"},{src:"assets/work/kiin/g8.jpg",cap_en:"Crunch in close-up",cap_ar:"القرمشة من قريب"},{src:"assets/work/kiin/g9.jpg",cap_en:"Three signatures in one hand",cap_ar:"تلت ساندوتشات في إيد واحدة"}],
       pdfs:[{file:"assets/work/kiin/kiin-ramadan-deck.pdf",label_en:"Ramadan campaign deck",label_ar:"عرض حملة رمضان"}]},
      {id:"takyt",cat:"content",brand:"Takyt Ons",logo:"assets/brands/takyt.png",region_en:"KSA",region_ar:"السعودية",sector_en:"Heritage Tea House",sector_ar:"بيت شاي تراثي",role_en:"Social Media Specialist & Content Writer",role_ar:"أخصائي سوشيال وكاتب محتوى",
       desc_en:"Ongoing content and copywriting for a Saudi heritage tea house — I wrote the captions, the seasonal calendars and the visual direction across Ramadan, both Eids, Founding Day and the summer cold-drinks push.",desc_ar:"محتوى وكوبي رايتنج مستمر لبيت شاي تراثي سعودي — كتبت الكابشن والكاليندرات الموسمية والتوجيه البصري عبر رمضان والعيدين واليوم الوطني وحملة المشروبات الباردة في الصيف.",
       challenge_en:"Build a content presence from the ground up — and give a quiet heritage brand a warm, consistent voice that stands out across seasons.",challenge_ar:"بناء حضور محتوى من الصفر — وإدّي براند تراثي هادي صوت دافي وثابت يبان عبر المواسم.",
       solution_en:"I built the content framework — objective, audience and tone — then a 10-post seasonal calendar with every caption and a visual-direction guide for the shoot, plus greeting and offer posts for Ramadan, Eid al-Fitr, Eid al-Adha and Saudi Founding Day.",solution_ar:"بنيت إطار المحتوى — الهدف، الجمهور والنبرة — وبعدها كاليندر موسمي ١٠ بوست بكل كابشن ودليل توجيه بصري للتصوير، زائد بوستات تهنئة وعروض لرمضان وعيد الفطر وعيد الأضحى واليوم الوطني السعودي.",
       metric_en:"Content package · 10-post calendar · seasonal greetings & offers",metric_ar:"حزمة محتوى · كاليندر ١٠ بوست · تهاني وعروض موسمية",
       about_en:"Takyt Ons (تكية أنس) is a Saudi heritage tea house — karak, sahlab, herbal teas and seasonal cold drinks served in a calm, traditional setting.",
       about_ar:"تكية أنس بيت شاي تراثي سعودي — كرك وسحلب وأعشاب ومشروبات باردة موسمية، تتقدّم في أجواء هادية تراثية.",
       services_en:["Content strategy","Copywriting","Seasonal calendar","Visual direction","Greeting & campaign posts","Hashtag strategy"],
       services_ar:["استراتيجية محتوى","كتابة محتوى","كاليندر موسمي","توجيه بصري","بوستات تهنئة وحملات","استراتيجية هاشتاجات"],
       results_en:["A full content framework — objective, target audience and brand voice","A 10-post seasonal calendar, every caption written end to end","A visual-direction guide that shaped the photography and styling","Greeting and offer posts across Ramadan, Eid al-Fitr, Eid al-Adha and Founding Day","A warm, heritage-first tone built for cold-drink season"],
       results_ar:["إطار محتوى كامل — الهدف والجمهور المستهدف وصوت البراند","كاليندر موسمي ١٠ بوست، كل كابشن مكتوب من الألف للياء","دليل توجيه بصري وجّه التصوير والاستايلينج","بوستات تهنئة وعروض عبر رمضان وعيد الفطر وعيد الأضحى واليوم الوطني","نبرة دافية تراثية مبنية لموسم المشروبات الباردة"],
       gallery:[{src:"assets/work/takyt/g1.jpg",cap_en:"Ramadan greeting post",cap_ar:"بوست تهنئة رمضان"},{src:"assets/work/takyt/g2.jpg",cap_en:"Eid al-Fitr greeting",cap_ar:"تهنئة عيد الفطر"},{src:"assets/work/takyt/g3.jpg",cap_en:"Eid al-Adha greeting",cap_ar:"تهنئة عيد الأضحى"},{src:"assets/work/takyt/g4.jpg",cap_en:"Founding Day offer — 3 jibati for the price of 2",cap_ar:"عرض اليوم الوطني — ٣ جباتي بسعر ٢"},{src:"assets/work/takyt/g5.jpg",cap_en:"Founding Day — a heritage story",cap_ar:"اليوم الوطني — حكاية تراث"},{src:"assets/work/takyt/g6.jpg",cap_en:"The signature tea tray",cap_ar:"صينية الشاي المميّزة"},{src:"assets/work/takyt/g7.jpg",cap_en:"The pour — a moment not to miss",cap_ar:"لحظة الصب — ما تتفوّت"},{src:"assets/work/takyt/g8.jpg",cap_en:"Karak in motion",cap_ar:"الكرك في الحركة"},{src:"assets/work/takyt/g9.jpg",cap_en:"A berry cold drink for summer",cap_ar:"مشروب توت بارد للصيف"},{src:"assets/work/takyt/g10.jpg",cap_en:"Tea by the water",cap_ar:"شاي على الماء"}],
       pdfs:[{file:"assets/work/takyt/takyt-content-deck.pdf",label_en:"Content & calendar deck",label_ar:"عرض المحتوى والكاليندر"}]},
      {id:"monacool",cat:"social",brand:"MonaCool",logo:"assets/brands/monacool.png",region_en:"Lebanon",region_ar:"لبنان",sector_en:"Natural Spring Water",sector_ar:"مياه نبع طبيعية",role_en:"Social Media Specialist & Content Writer",role_ar:"أخصائي سوشيال وكاتب محتوى",
       desc_en:"Ramadan content campaign and a new-product launch for a natural-spring-water brand — I wrote the brief, the key messages, the post calendar and the launch concept around one idea: healthy hydration is the secret to energy through the fast.",desc_ar:"حملة محتوى رمضانية وإطلاق منتج جديد لبراند مياه نبع طبيعية — كتبت البريف والرسائل الرئيسية وكاليندر البوستات وكونسبت الإطلاق حوالين فكرة واحدة: الترطيب الصحي هو سر الطاقة في الصيام.",
       challenge_en:"Stand out in a crowded Ramadan water market and own a clear role: the brand that keeps families hydrated through iftar, suhoor and taraweeh.",challenge_ar:"تتميّز في سوق مياه رمضان المزدحم وتملك دور واضح: البراند اللي يحافظ على ترطيب العيلة في الإفطار والسحور والتراويح.",
       solution_en:"I built the Ramadan campaign — objective, audience, key messages and a warm instructional tone — then a 12-post calendar with captions, hashtags and design briefs, plus a separate launch plan for the new 0.5L glass bottle (teaser, video concept and reveal copy).",solution_ar:"بنيت حملة رمضان — الهدف، الجمهور، الرسائل الرئيسية ونبرة دافية إرشادية — وبعدها كاليندر ١٢ بوست بالكابشن والهاشتاجات وبريفات الديزاين، زائد خطة إطلاق منفصلة للقارورة الزجاجية الجديدة ٠.٥ لتر (تشويق + كونسبت فيديو + كوبي الكشف).",
       metric_en:"Ramadan campaign · 12-post calendar · new-product launch",metric_ar:"حملة رمضان · كاليندر ١٢ بوست · إطلاق منتج جديد",
       about_en:"MonaCool is a natural spring water brand — large home-and-office bottles plus a new 0.5L line — positioned around purity and healthy hydration.",
       about_ar:"MonaCool براند مياه نبع طبيعية — قارورات منزلية وحجم عائلي بالإضافة لخط جديد ٠.٥ لتر — متموضع حوالين النقاء والترطيب الصحي.",
       services_en:["Content strategy","Campaign brief","Copywriting","Social calendar","Product launch concept","Hashtag strategy"],
       services_ar:["استراتيجية محتوى","بريف حملة","كتابة محتوى","كاليندر سوشيال","كونسبت إطلاق منتج","استراتيجية هاشتاجات"],
       results_en:["A full Ramadan campaign brief — objective, audience and five key messages","A 12-post calendar with captions, hashtags and a design brief for each","A warm, instructional tone built around healthy hydration (iftar, suhoor, taraweeh)","A separate launch plan for the new 0.5L glass bottle — teaser, video concept and reveal copy","Greeting posts for Ramadan and Eid that tie the brand to family moments"],
       results_ar:["بريف حملة رمضان كامل — الهدف والجمهور وخمس رسائل رئيسية","كاليندر ١٢ بوست بالكابشن والهاشتاجات وبريف ديزاين لكل واحد","نبرة دافية إرشادية مبنية على الترطيب الصحي (إفطار، سحور، تراويح)","خطة إطلاق منفصلة للقارورة الزجاجية الجديدة ٠.٥ لتر — تشويق وكونسبت فيديو وكوبي الكشف","بوستات تهنئة لرمضان والعيد تربط البراند بلحظات العيلة"],
       gallery:[{src:"assets/work/monacool/g1.jpg",cap_en:"Ramadan greeting post",cap_ar:"بوست تهنئة رمضان"},{src:"assets/work/monacool/g2.jpg",cap_en:"\"Iftar brings us together\"",cap_ar:"«الإفطار يجمعنا»"},{src:"assets/work/monacool/g3.jpg",cap_en:"\"Balance your energy with MonaCool\"",cap_ar:"«وازن طاقتك مع MonaCool»"},{src:"assets/work/monacool/g4.jpg",cap_en:"Eid greeting post",cap_ar:"بوست تهنئة العيد"},{src:"assets/work/monacool/g5.jpg",cap_en:"\"Healthy suhoor for an easy fast\"",cap_ar:"«سحور صحي لصيام مريح»"},{src:"assets/work/monacool/g6.jpg",cap_en:"\"Thirsty? Avoid dehydration\"",cap_ar:"«عطشان؟ تجنّب الجفاف»"},{src:"assets/work/monacool/g7.jpg",cap_en:"Hydration tips — water is energy in Ramadan",cap_ar:"نصائح ترطيب — الماء سر الطاقة في رمضان"}],
       pdfs:[{file:"assets/work/monacool/monacool-ramadan-deck.pdf",label_en:"Ramadan campaign deck",label_ar:"عرض حملة رمضان"},{file:"assets/work/monacool/monacool-new-product.pdf",label_en:"New-product launch concept",label_ar:"كونسبت إطلاق المنتج الجديد"}]},
      {id:"voiceover",cat:"voice",brand:"Voice-Over",logo:"assets/brands/voiceover.png",region_en:"KSA",region_ar:"السعودية",sector_en:"Voice-Over & Scriptwriting",sector_ar:"تعليق صوتي وكتابة سكربت",role_en:"Voice-Over Artist & Scriptwriter",role_ar:"معلّق صوتي وكاتب سكربت",
       desc_en:"Voice-over and scriptwriting in Saudi dialect across brands including Aku Shawerma and Al-Mustashar — I write the scripts, perform the voice-over, and step in front of the camera when the piece needs a face.",desc_ar:"تعليق صوتي وكتابة سكربت باللهجة السعودية لبراندات منها اكو شاورما والمستشار — بكتب السكربت، بأدّي التعليق الصوتي، وبوقف قدام الكاميرا لما المحتوى يحتاج وش.",
       challenge_en:"Deliver authentic, end-to-end Saudi-dialect video content — script, voice and on-camera presence — for more than one brand.",challenge_ar:"تقديم محتوى فيديو سعودي أصيل من الألف للياء — سكربت وصوت وظهور كاميرا — لأكتر من براند.",
       solution_en:"I mastered the Saudi dialect and owned the work end to end: writing the scripts, recording the voice-over, and presenting on camera when needed.",solution_ar:"أتقنت اللهجة السعودية واشتغلت على الشغل كامل: كتابة السكربتات، تسجيل التعليق الصوتي، والتقديم قدام الكاميرا لما يلزم.",
       metric_en:"Voice-over & scriptwriting · Saudi dialect · on-camera",metric_ar:"تعليق صوتي وكتابة سكربت · لهجة سعودية · ظهور كاميرا",
       about_en:"A voice-over and scriptwriting track spanning more than one brand — among them Aku Shawerma and Al-Mustashar — all delivered in authentic Saudi dialect.",
       about_ar:"مسار تعليق صوتي وكتابة سكربت يغطّي أكتر من براند — منهم اكو شاورما والمستشار — كله باللهجة السعودية الأصيلة.",
       services_en:["Voice-over","Scriptwriting","On-camera presenting","Saudi-dialect delivery"],
       services_ar:["تعليق صوتي","كتابة سكربت","تقديم أمام الكاميرا","أداء باللهجة السعودية"],
       results_en:["Al-Mustashar — five scripts written and voiced, with on-camera appearances in two","Aku Shawerma — a tasting-style ad, scripted and voiced in Saudi dialect","End-to-end ownership: script, voice and on-camera presence"],
       results_ar:["المستشار — خمس سكربتات اتكتبت واتعمَلها تعليق صوتي، مع ظهور قدام الكاميرا في اتنين","اكو شاورما — إعلان تجربة، كتابة وتعليق صوتي باللهجة السعودية","مسؤولية كاملة: سكربت وصوت وظهور كاميرا"],
       videos:[{src:"assets/work/voiceover/almustashar-v1.mp4",poster:"assets/work/voiceover/almustashar-v1-poster.jpg",cap_en:"Al-Mustashar — company-formation ad I scripted and voiced",cap_ar:"المستشار — إعلان تأسيس الشركات اللي كتبته وعملتله تعليق صوتي"},{src:"assets/work/voiceover/almustashar-v2.mp4",poster:"assets/work/voiceover/almustashar-v2-poster.jpg",cap_en:"Al-Mustashar — services ad, scripted and voiced",cap_ar:"المستشار — إعلان الخدمات، كتابة وتعليق صوتي"},{src:"assets/work/voiceover/aku-shawerma.mp4",poster:"assets/work/voiceover/aku-shawerma-poster.jpg",cap_en:"Aku Shawerma — a tasting-style ad I scripted and voiced",cap_ar:"اكو شاورما — إعلان على طريقة التجربة، كتابة وتعليق صوتي"}],
       pdfs:[{file:"assets/work/voiceover/almustashar-scripts.pdf",label_en:"Al-Mustashar — the scripts I wrote",label_ar:"المستشار — السكربتات اللي كتبتها"},{file:"assets/work/voiceover/aku-shawerma-script.pdf",label_en:"Aku Shawerma — the script I wrote",label_ar:"اكو شاورما — السكربت اللي كتبته"}]},
      {id:"almanara",cat:"content",brand:"Al-Manara",logo:"assets/brands/almanara.png",region_en:"KSA",region_ar:"السعودية",sector_en:"Marketing Agency",sector_ar:"وكالة تسويق",role_en:"Content Specialist & Account Coordinator",role_ar:"أخصائي محتوى ومنسّق حسابات",
       desc_en:"Content and account work at a marketing agency — clearing a backlog of overdue client tasks, producing company-profile campaigns and website content, and improving how the agency runs.",desc_ar:"شغل محتوى وتنسيق حسابات في وكالة تسويق — ترتيب تاسكات عملاء متأخرة، إنتاج كامبينات بروفايل ومحتوى مواقع، وتحسين طريقة شغل الوكالة.",
       challenge_en:"A backlog of delayed client tasks, published content that needed lifting, and operations that needed clearer structure.",challenge_ar:"تاسكات عملاء متأخرة ومتراكمة، محتوى منشور محتاج تحسين، وأوبريشن محتاج ترتيب أوضح.",
       solution_en:"I started by re-prioritising the clients with overdue tasks, then delivered three full company-profile campaigns and content for three websites, and improved the published content for active clients. I followed up closely with the design team and the website-UI designers, and gave the agency executable suggestions to develop its operation and improve the client experience.",solution_ar:"بدأت بترتيب أولويات العملاء اللي تاسكاتهم متأخرة، وبعدها سلّمت ٣ كامبينات بروفايل كاملة ومحتوى ٣ مواقع إلكترونية، وحسّنت المحتوى المنشور للعملاء الحاليين. تابعت عن قرب مع فريق التصميم ومصممي واجهات المواقع، وقدّمت للوكالة اقتراحات تنفيذية لتطوير الأوبريشن وتحسين تجربة العملاء.",
       metric_en:"3 company-profile campaigns · content for 3 websites",metric_ar:"٣ كامبينات بروفايل · محتوى ٣ مواقع",
       about_en:"Al-Manara (The Minaret, @theminaretagency) is a marketing agency. I work across content, client coordination and operational improvements.",
       about_ar:"المنارة (The Minaret، @theminaretagency) وكالة تسويق. بشتغل على المحتوى وتنسيق الحسابات وتحسين الأوبريشن.",
       services_en:["Content writing","Company-profile campaigns","Website copy","Content optimization","Client coordination","Design-team follow-up","Operations & process suggestions"],
       services_ar:["كتابة محتوى","كامبينات بروفايل","محتوى مواقع إلكترونية","تحسين المحتوى","تنسيق حسابات العملاء","متابعة فريق التصميم","اقتراحات أوبريشن وعمليات"],
       results_en:["Re-prioritised and cleared a backlog of overdue client tasks","Three complete company-profile campaigns delivered to date","Content written for three websites","Improved published content for active clients","Close follow-up with the design and website-UI teams","Executable suggestions that improved the agency's operation and client experience"],
       results_ar:["إعادة ترتيب وتصفية تاسكات عملاء كانت متأخرة","٣ كامبينات بروفايل كاملة متسلّمة لحد دلوقتي","محتوى مكتوب لـ ٣ مواقع إلكترونية","تحسين المحتوى المنشور للعملاء الحاليين","متابعة لصيقة مع فريق التصميم ومصممي واجهات المواقع","اقتراحات تنفيذية حسّنت أوبريشن الوكالة وتجربة العملاء"],
       links:[{url:"https://theminaretagency.com/",label_en:"Website",label_ar:"الموقع"},{url:"https://www.instagram.com/theminaretagency",label_en:"Instagram",label_ar:"إنستجرام"}],
       subprojects:[
         {title_en:"Shajan",title_ar:"شجن",note_en:"Construction-waste container rental in Riyadh — full website copy across home, about, services, projects and contact.",note_ar:"تأجير حاويات مخلفات بناء بالرياض — كتابة محتوى الموقع كامل: الرئيسية، من نحن، الخدمات، سوابق الأعمال، وتواصل.",thumb:"assets/work/almanara/shajan-cover.jpg",pdf:"assets/work/almanara/shajan-website-content.pdf",link:"https://shajan1.com/"},
         {title_en:"SulConsult Group (SCG)",title_ar:"مجموعة سل كونسلت (SCG)",note_en:"Corporate consulting firm in Taif — company profile: who we are, vision, values, services and target sectors.",note_ar:"شركة استشارات مؤسسية بالطائف — الملف التعريفي: من نحن، الرؤية، القيم، الخدمات، والفئات المستهدفة.",thumb:"assets/work/almanara/scg-cover.jpg",pdf:"assets/work/almanara/scg-profile.pdf",link:"https://scg-s.com/"},
         {title_en:"One Care",title_ar:"ون كير",note_en:"Digital booking platform for clinics and beauty salons in KSA — full company profile and messaging.",note_ar:"منصة حجوزات رقمية للعيادات وصالونات التجميل بالسعودية — الملف التعريفي والرسائل كاملة.",thumb:"assets/work/almanara/onecare-cover.jpg",pdf:"assets/work/almanara/onecare-profile.pdf"}
       ]},
      {id:"qumra",cat:"strategy",brand:"Qumra",logo:"assets/brands/qumra.png",region_en:"Egypt",region_ar:"مصر",sector_en:"E-commerce SaaS Platform",sector_ar:"منصة SaaS للتجارة الإلكترونية",role_en:"Content Strategist & Community Manager",role_ar:"استراتيجي محتوى ومدير مجتمع",
       desc_en:"Content strategy, platform optimization, paid ads and merchant-community management for an e-commerce SaaS platform — work that pushed sign-ups to the highest numbers in the platform's history.",desc_ar:"استراتيجية محتوى، تحسين المنصة، إعلانات، وإدارة مجتمع التجار لمنصة SaaS للتجارة الإلكترونية — شغل وصل بأرقام التسجيل لأعلى مستوى في تاريخ المنصة.",
       challenge_en:"The ad creative was burnt out and long overdue for a refresh, sign-ups had stalled, and content, design and publishing had no clear system to run on.",challenge_ar:"الكرييتيف الإعلاني كان مستهلك وعدّى عليه زمن من غير تجديد، التسجيلات واقفة، والمحتوى والتصميم والنشر مفيش ليهم نظام واضح يمشوا عليه.",
       solution_en:"I rebuilt the ad creative from scratch, improved the platform's user experience, and set up a clear system for design, content and publishing. I proposed a long list of platform-development ideas — now in implementation — and hired and trained a sales team and a moderator team on the right way to respond, so they convert the most subscriptions and stores.",solution_ar:"أعدت بناء الكرييتيف الإعلاني من الصفر، حسّنت تجربة المستخدم على المنصة، وعملت نظام واضح للتصميم والمحتوى والنشر. وعرضت أفكار كتير لتطوير المنصة — بتتنفّذ حاليًا — ووظّفت ودرّبت فريق مبيعات وتيم مودريتورز على طريقة الرد الصح، عشان يحقّقوا أكبر عدد اشتراكات ومتاجر.",
       metric_en:"Highest sign-ups in the platform's history",metric_ar:"أعلى تسجيلات في تاريخ المنصة",
       about_en:"Qumra is an Egyptian e-commerce SaaS platform that lets merchants build and run their own online stores — in the same space as Shopify, Salla, Zid and Zammit.",
       about_ar:"قمرة منصة SaaS مصرية للتجارة الإلكترونية بتخلّي التاجر يبني ويدير متجره الإلكتروني — في نفس مجال شوبيفاي وسلة وزد وزامت.",
       services_en:["Content strategy","Platform UX","Paid ads & creative","Community management","Design & publishing system","Platform-growth ideas","Sales & moderation team building","Team training"],
       services_ar:["استراتيجية محتوى","تحسين تجربة المستخدم","إعلانات وكرييتيف","إدارة مجتمع","نظام تصميم ونشر","أفكار تطوير المنصة","بناء فريق مبيعات ومودريشن","تدريب الفريق"],
       results_en:["The highest number of sign-ups in the platform's history since I joined","A fully rebuilt ad creative after the previous one had burnt out","A clear, repeatable system for design, content and publishing","A backlog of platform-development ideas — now in implementation","A hired and trained sales + moderation team, briefed on a response style that maximises subscriptions and stores"],
       results_ar:["أعلى عدد تسجيلات في تاريخ المنصة من ساعة ما بدأت","كرييتيف إعلاني جديد بالكامل بعد ما القديم كان «محروق»","نظام واضح ومتكرّر للتصميم والمحتوى والنشر","قائمة أفكار لتطوير المنصة — بتتنفّذ حاليًا","فريق مبيعات ومودريشن متوظّف ومتدرّب على أسلوب رد بيزوّد الاشتراكات والمتاجر"],
       links:[{url:"https://qumra.cloud/",label_en:"Qumra platform",label_ar:"منصة قمرة"}]},
    ],
    modal_challenge_en:"Challenge",modal_challenge_ar:"التحدّي",
    modal_solution_en:"What I did",modal_solution_ar:"اللي عملته",
    modal_result_en:"Result",modal_result_ar:"النتيجة",

    /* ===== لافتات صفحة العميل المستقلة (case.html) ===== */
    case_back_en:"All work", case_back_ar:"كل الشغل",
    case_about_en:"About the client", case_about_ar:"عن العميل",
    case_role_label_en:"My role", case_role_label_ar:"دوري",
    case_duration_label_en:"Duration", case_duration_label_ar:"المدة",
    case_market_label_en:"Market", case_market_label_ar:"السوق",
    case_services_en:"What I provided", case_services_ar:"اللي قدّمته",
    case_did_en:"The challenge & what I did", case_did_ar:"التحدّي واللي عملته",
    case_results_en:"Results", case_results_ar:"النتايج",
    case_work_en:"The work", case_work_ar:"الشغل نفسه",
    case_pdf_en:"Documents", case_pdf_ar:"ملفات",
    case_view_pdf_en:"Open file", case_view_pdf_ar:"افتح الملف",
    case_links_en:"Live links", case_links_ar:"روابط مباشرة",
    case_empty_en:"Work samples for this project are coming soon.", case_empty_ar:"نماذج شغل المشروع ده هتتضاف قريب.",
    case_next_en:"Next project", case_next_ar:"المشروع اللي بعده",
    case_prev_en:"Previous project", case_prev_ar:"المشروع اللي قبله",
    case_cta_h_en:"Want results like these for your brand?", case_cta_h_ar:"عايز نتايج زي دي لبراندك؟",
    case_cta_btn_en:"Let's talk", case_cta_btn_ar:"يلا نتكلم",
    wall_h_en:"Brands I've worked with", wall_h_ar:"براندات اشتغلت معاها",
    close_en:"The road ahead looked dark — let me light it up with the results above.",
    close_ar:"الطريق قدامك كان ضلمة، تعالى أنوّرهولك بنتايج الشغل اللي فوق.",
  },

  /* ===== شريط/حائط البراندات. اللي ليه لوجو حطّ الباث، والباقي اسم بس ===== */
  brands:[
    {n:"Mantorose",l:"assets/brands/mantorose.png"},{n:"A_ONE",l:"assets/brands/aone.png"},
    {n:"Sitdown",l:"assets/brands/sitdown.png"},{n:"Karam Inn",l:"assets/brands/karaminn.png"},
    {n:"Broasted Karam",l:"assets/brands/broasted.png"},{n:"KIIN",l:"assets/brands/kiin.png"},
    {n:"Takyt Ons",l:"assets/brands/takyt.png"},{n:"MonaCool",l:"assets/brands/monacool.png"},
    {n:"Al-Mustashar",l:"assets/brands/almustashar.png"},{n:"Aku Shawerma"},{n:"Pioneers"},{n:"RAK therm"},
    {n:"Baby Goo"},{n:"Ship It"},{n:"Dr Diet"},{n:"Karizma"},{n:"Aram"},{n:"Dana"},
  ],

  /* ===== 10) الخدمات (Services) ===== */
  services: {
    eyebrow_en:"Services", eyebrow_ar:"الخدمات",
    title_en:"What can I actually do?", title_ar:"أنا بعرف أعمل إيه؟",
    lead_en:"It comes down to three things: communication, strategy, and execution. Here's what I know well, what I'm developing right now, and the tools I use.",
    lead_ar:"ممكن نختصرهم في ثلاث حاجات: التواصل، الاستراتيجية، والتنفيذ. بس أنا هتكلم عن اللي عارفه كويس، اللي بطوّره حاليًا، والأدوات اللي بستخدمها.",
    tiers:[
      {h_en:"Services I offer", h_ar:"الخدمات اللي بقدّمها", lead:true, groups:[
        {t_en:"Content Strategy",t_ar:"استراتيجية المحتوى",items_en:["Building content strategies","Content pillars","Content calendars","Seasonal campaign planning","Marketing ideas & initiatives"],items_ar:["بناء استراتيجيات المحتوى","تحديد Content Pillars","إعداد Content Calendars","تخطيط الحملات الموسمية","تطوير الأفكار والمبادرات"]},
        {t_en:"Social Media Management",t_ar:"إدارة السوشيال ميديا",items_en:["Account management","Leading & organizing content teams","Overseeing plan execution","Performance analysis & recommendations"],items_ar:["إدارة حسابات التواصل","تنظيم وإدارة فرق المحتوى","متابعة تنفيذ الخطط","تحليل الأداء وتقديم التوصيات"]},
        {t_en:"Copywriting & Scriptwriting",t_ar:"الكتابة والسكربتات",items_en:["Marketing copy","Ad copy","Video scripts","Social media content","Proposals & pitches"],items_ar:["المحتوى التسويقي","الإعلانات","سيناريوهات الفيديو","محتوى السوشيال","العروض والبروبوزالز"]},
        {t_en:"Marketing Strategy",t_ar:"الاستراتيجية التسويقية",items_en:["Brand & market analysis","Audience targeting","Messaging","Marketing plans","Offer & service development"],items_ar:["تحليل البراند والسوق","تحديد الجمهور المستهدف","بناء الرسائل","إعداد الخطط","تطوير العروض والخدمات"]},
        {t_en:"Personal Branding",t_ar:"العلامة الشخصية",items_en:["Personal identity","Personal message","Content strategy for experts & founders","LinkedIn content strategy"],items_ar:["بناء الهوية الشخصية","تطوير الرسالة الشخصية","استراتيجية محتوى للخبراء وأصحاب الأعمال","LinkedIn Content Strategy"]},
        {t_en:"Marketing Operations",t_ar:"عمليات التسويق",items_en:["Organizing marketing operations","Building processes & workflows","Marketing project management","Cross-team coordination"],items_ar:["تنظيم العمليات التسويقية","بناء الإجراءات وسير العمل","إدارة المشاريع التسويقية","تنسيق العمل بين الفرق"]},
        {t_en:"Performance Analysis",t_ar:"تحليل الأداء",items_en:["Marketing performance analysis","Reporting","KPI tracking","Optimization recommendations"],items_ar:["تحليل الأداء التسويقي","إعداد التقارير","متابعة مؤشرات الأداء (KPIs)","توصيات التحسين"]},
      ]},
      {h_en:"Strong working knowledge", h_ar:"معرفة جيدة بها", groups:[
        {t_en:"Business & Operations",t_ar:"الأعمال والتشغيل",items_en:["Pricing","Packages & services","Operations","Accounting basics"],items_ar:["التسعير","تطوير الباقات والخدمات","العمليات التشغيلية","أساسيات المحاسبة"]},
        {t_en:"E-Commerce",t_ar:"التجارة الإلكترونية",items_en:["Store management","Store UX","Landing pages","Products & offers"],items_ar:["إدارة وتشغيل المتاجر","تجربة المستخدم للمتاجر","صفحات الهبوط","إدارة المنتجات والعروض"]},
        {t_en:"Web & CMS",t_ar:"الويب والـ CMS",items_en:["WordPress","WooCommerce","Content & site management"],items_ar:["WordPress","WooCommerce","إدارة المحتوى والمواقع"]},
      ]},
      {h_en:"Currently developing", h_ar:"أطوّر نفسي فيها حاليًا", chips:true, groups:[
        {t_en:"Performance Marketing",t_ar:"Performance Marketing",items_en:["Meta Ads","Media Buying","Campaign Optimization"]},
        {t_en:"SEO",t_ar:"SEO",items_en:["Keyword Research","On-Page SEO","Content SEO"]},
        {t_en:"Marketing Automation",t_ar:"Marketing Automation",items_en:["Workflow Automation","Customer Journey","CRM Fundamentals"]},
        {t_en:"AI for Marketing",t_ar:"AI for Marketing",items_en:["Prompt Engineering","AI Content Systems","AI-Assisted Marketing"]},
        {t_en:"Data & Analytics",t_ar:"Data & Analytics",items_en:["Marketing Analytics","Dashboard Building","Data Interpretation"]},
        {t_en:"Technical Skills",t_ar:"Technical Skills",items_en:["Python","Programming basics","Digital systems & platforms"]},
      ]},
      {h_en:"Tools I use", h_ar:"الأدوات اللي بستخدمها", chips:true, groups:[
        {t_en:"Marketing & Analytics",t_ar:"Marketing & Analytics",items_en:["Meta Business Suite","Google Analytics","Search Console","Google Trends"]},
        {t_en:"Productivity",t_ar:"Productivity",items_en:["Notion","Google Workspace","Microsoft Office","Excel"]},
        {t_en:"AI",t_ar:"AI",items_en:["ChatGPT","Claude","Gemini","Perplexity"]},
        {t_en:"Design & Creative",t_ar:"Design & Creative",items_en:["Canva","Photoshop","Filmora","CapCut"]},
        {t_en:"Web & E-Commerce",t_ar:"Web & E-Commerce",items_en:["WordPress","WooCommerce","Qumra Cloud"]},
      ]},
    ],
  },

  /* ===== 11) تواصل (Contact) ===== */
  contact: {
    eyebrow_en:"Contact", eyebrow_ar:"تواصل",
    title_en:"Let's move your brand from chaos to clarity.", title_ar:"خلّينا ننقل براندك من التشتت للوضوح.",
    sub_en:"Whether you're starting, scaling, or lost in the market — there's always a way. Because we should always try one more time.",
    sub_ar:"سواء بتبدأ، بتكبّر، أو ضايع وسط السوق — دايمًا هنلاقي حل، عشان المفروض نحاول كمان مرة.",
    email_label_en:"Email",email_label_ar:"إيميل",
    wa_label_en:"WhatsApp",wa_label_ar:"واتساب",
    in_label_en:"LinkedIn",in_label_ar:"لينكد إن",
    loc_label_en:"Based in",loc_label_ar:"المقر",
  },

  footer_en:"© 2026 Abdullah Basyoni — Try one more time.",
  footer_ar:"© 2026 عبدالله بسيوني — حاول كمان مرة.",
};
